name: Build

on:
  push:
    branches: ["**"]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.configuration }} | ${{ matrix.platform }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        configuration: [Release]
        platform: [amd64]
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Set up MSVC env
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Build solution
        shell: pwsh
        run: >
          msbuild .\wintun.sln -m
          -p:Configuration=${{ matrix.configuration }}
          -p:Platform=${{ matrix.platform }}

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wintun-${{ matrix.configuration }}-${{ matrix.platform }}
          path: |
            ${{ matrix.configuration }}/**
          retention-days: 7
